### ISSUE TITLE
Multiple Array Types implementation

### ISSUE THREAD

**Issue by chevEldrid** [ncraffey/Part2#19]
Hey, so it looks like things are going in the way of having separate definitions for each type of array we can create... https://piazza.com/class/k51bluky59n2jr?cid=331

Could you build out specifications for each other array type and tests to match?

**Comment by laposata** [comment]
I will get on this soon, I cant at this very minute but i should tonight if not tomorrow morning, in the mean time know the headers will be the same just returning/taking  the respective classes

**Comment by laposata** [comment]
updated
