### ISSUE TITLE
Arrays in tests have to be pointers

### ISSUE THREAD

**Issue by chevEldrid** [ncraffey/Part2#21]
test-array.cpp:27:15: error: conversion from ‘Array*’ to non-scalar type ‘Array’ requested
     Array d = new Array(3, sizeof(String));

(getting the following error when trying to compile your tests-I believe you need to change Array d to "Array* d")

**Comment by chevEldrid** [comment]
This also ties into the method calls to Array.length which should then be d->length()

**Comment by laposata** [comment]
i was inconsistent by using -> when array was not a pointer, made change on ll but length, that should work as its consistent
