### ISSUE TITLE
inconsistent hash behavior

### ISSUE THREAD

**Issue by chevEldrid** [ncraffey/Part2#23]
Hey,

I remember asking about this test before but...

void objectHashTest(){
    Object* a = new String("hello");
    Object* b = new String("hello");
    Object* c = new String("no hello");
    assert(a->hash() == a->hash());
    assert(a->hash() != b->hash());
};

..is this really the behavior we want? Shouldn't a and b have the same hash since they're the same string? In this current implementation hash would only return true if the objects are the same which kind of defeats the purpose. 

Could you change the second test to see a->hash() != c->hash())?

**Comment by laposata** [comment]
yes, sorry fixed all issues together last time, you  are right i didnt do this right, resolved again
