### ISSUE TITLE
Can't override methods with different return types

### ISSUE THREAD

**Issue by chevEldrid** [ncraffey/Part2#27]
Hey guys, 
so while the strategy of having a base Array class and implementing off of it is good...it doesn't really work for the primitive types since they're not of class Object. i.e.
`return type is not identical to nor covariant with return type "Object *" of overridden virtual function "Array::get"`

This is what happens when you try to implement the int array claiming it inherits from the Array class. I believe you have to just build them out from scratch separately and have them all inherit from Object.

**Comment by laposata** [comment]
okay, I personally really dont want that amount of code duplication, so i set the array class to return void* and created an object array class, this should mean you can implement once in the void class and then just call those with casts in the others. C++ is not my strongest language so let me know if this doesnt work. Also if you want to go back and forth a bit faster i'm Michael Laposata and im usually on messenger

**Comment by davidfstein** [comment]
Can you explain the intended usage? Why are the ObjArray methods virtual?
