### ISSUE TITLE
CwC does not allow for Union types

### ISSUE THREAD

**Issue by EricXuZh** [ncraffey/Part2#46]
I believe CwC does not allow for Union types; I believe object should encompass everything. For primitive types, it simply suffices to make a wrapper class for them (similar to what is seen in Java)

**Comment by chevEldrid** [comment]
Yeah from everything I've seen unions run hand in hand with structs and require some sort of generics to discern type of the element in the union that has a value associated with it. It would be much easier to just wrap primitive types in object
